---
- hosts: mywebservers
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: install webserver on redhat
      yum:
        service: httpd
        state: present
      notify: starthttpd
      when: ansible_os_family=="RedHat" 
      
    - name: copy file from cm to node
      template:
        src: myindex.j2
        dest: /var/www/html/index.html
      notify: starthttpd
      when: ansible_os_family=="RedHat"
      
      
  handlers:
    - name: starthttpd
      service:
        name: httpd
        state: started
